import { useUserQuery } from "@/generated/graphql";
import { useQuery, gql } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";

const USER = gql`
  query user($userId: String!) {
    user(id: $userId) {
      id
      email
      posts {
        id
        title
      }
    }
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>nest-next-graphql</p>
    </div>
  );
};

export default Home;
