import { useQuery, gql } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";

const USER = gql`
  query user {
    user(id: "ckysd3b2t0004vzuwnetxasrt") {
      id
      email
      posts {
        id
        title
      }
    }
  }
`;

const Home: NextPage = () => {
  const { data, error, loading } = useQuery(USER);
  console.log({ data, error, loading });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>nest-next-graphql</p>
    </div>
  );
};

export default Home;
